# Generated by Django 4.1.3 on 2023-02-10 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo1', '0002_timestamps_timestamps1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postforo',
            options={'managed': False, 'ordering': ['Timestamps']},
        ),
    ]
