# Generated by Django 4.1.3 on 2023-02-10 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo1', '0003_alter_postforo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'managed': False, 'ordering': ['Timestamps']},
        ),
        migrations.AlterModelOptions(
            name='imagen',
            options={'managed': False, 'ordering': ['Timestamps']},
        ),
        migrations.AlterModelOptions(
            name='postforo',
            options={'managed': False},
        ),
    ]
