# Generated by Django 4.1.3 on 2023-02-11 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo1', '0004_alter_comentario_options_alter_imagen_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='imagen',
            options={'managed': False},
        ),
    ]
