# Generated by Django 4.1.3 on 2023-02-11 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo1', '0005_alter_comentario_options_alter_imagen_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timestamps',
        ),
        migrations.DeleteModel(
            name='Timestamps1',
        ),
    ]
