# Generated by Django 4.1.3 on 2023-02-12 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo1', '0006_delete_timestamps_delete_timestamps1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'managed': False, 'ordering': ['-fechahoracoment']},
        ),
        migrations.AlterModelOptions(
            name='imagen',
            options={'managed': False, 'ordering': ['-fechahoraimg']},
        ),
    ]
