# Generated by Django 4.1.3 on 2023-02-13 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo1', '0008_alter_comentario_options_alter_imagen_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'managed': False, 'ordering': ['-fechahoracoment']},
        ),
        migrations.AlterModelOptions(
            name='imagen',
            options={'managed': False, 'ordering': ['-fechahoraimg']},
        ),
    ]
