# Generated by Django 4.1.3 on 2023-02-14 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo1', '0009_alter_comentario_options_alter_imagen_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historial',
            options={'managed': False, 'ordering': ['-fecha']},
        ),
    ]
