# Generated by Django 4.1.3 on 2023-02-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo1', '0010_alter_historial_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timestamps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'timestamps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timestamps1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'timestamps_1',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Registrarseforoperfilforo',
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='historial',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='imagen',
            options={'managed': False},
        ),
    ]
