# Generated by Django 4.1.3 on 2023-02-15 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo1', '0011_timestamps_timestamps1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'managed': False, 'ordering': ['-fechahoracoment']},
        ),
        migrations.AlterModelOptions(
            name='imagen',
            options={'managed': False, 'ordering': ['-fechahoraimg']},
        ),
    ]
